name: anyhow
description: Inspired by Rust's "anyhow" crate, this Dart package provides versatile error handling, implementing 
  Rust's Result monad and "anyhow" crate functionality
version: 0.6.2
repository: https://github.com/mcmah309/anyhow

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  test: any
