name: anyhow
description: Idiomatic error handling in Dart. Anyhow attempts to be a full implementation of Rust's Anyhow crate and 
  more. This package contains a Result monad, functions for wrapping code that may throw into result, exception 
  chaining, panics, various extensions, and more.
version: 0.3.1
repository: https://github.com/mcmah309/anyhow

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.10.0

dev_dependencies:
  test: any
