name: anyhow
description: Versatile and idiomatic error handling capabilities to make your code safer, more maintainable, and errors
  easier to debug. Dart implementation of Rust's Result monad type and "anyhow" crate.
version: 0.8.0
repository: https://github.com/mcmah309/anyhow

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  test: any
